# Extend Airbnb default config without React
extends:
  - airbnb-base
  - airbnb-typescript/base

parserOptions:
  ecmaVersion: 13
  project: './tsconfig.json'

env:
  browser: true

rules:
  arrow-parens:
    - error
    - as-needed
  curly:
    - error
    - all
  max-len:
    - error
    -
      code: 140
      tabWidth: 2
      ignoreComments: true
  no-param-reassign:
    - error
    -
      props: false
  '@typescript-eslint/explicit-function-return-type': off

overrides:
  -
    files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/explicit-function-return-type': ['error']
