exclude_paths:
  - db
  - config

detectors:
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    max_statements: 7

# Recommended configuration for Rails
# As per https://github.com/troessner/reek#working-with-rails
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
    TooManyStatements:
      max_statements: 10
    DuplicateMethodCall:
      allow_calls:
        - format.html
        - format.json

  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false

  "app/mailers":
    InstanceVariableAssumption:
      enabled: false

  "app/models":
    InstanceVariableAssumption:
      enabled: false
