require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - config/**/*
    - test/**/*
    - node_modules/**/*


Bundler/OrderedGems:
  Enabled: false

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable
Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods
Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
# Ensures a trailing new line
Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline
Layout/LineLength:
  Max: 140

# Document classes and non-namespace modules.
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded
# Checks if there is a magic comment to enforce string literals
Style/FrozenStringLiteralComment:
  Enabled: false
# Use brackets for arrays of symbols.
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
# Use brackets for arrays of words.
Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

# Rails specific rules
Rails:
  Enabled: true
Rails/Blank:
  UnlessPresent: false
