version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      target: prod
    environment:
      DATABASE_URL: "postgres://postgres:password@db/aktenkoffer"
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
