version: 2

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:3.1.0-node
    steps:
      - checkout
      - run: bundle
      - run:
          name: RuboCop
          command: |
            bundle exec rubocop .
  eslint:
    docker:
      - image: circleci/ruby:3.1.0-node
    steps:
      - checkout
      - run: yarn
      - run:
          name: ESLint
          command: |
            yarn lint
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  rubocop:
    jobs:
      - rubocop
  eslint:
    jobs:
      - eslint
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
