version: 2

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.1.0-node
    steps:
      - checkout
      - run: bundle
      - run:
          name: RuboCop
          command: |
            bundle exec rubocop .
  eslint:
    docker:
      - image: cimg/ruby:3.1.0-node
    steps:
      - checkout
      - run: yarn
      - run:
          name: Lint JavaScript & Typescript assets
          command: |
            yarn lint

workflows:
  version: 2
  rubocop:
    jobs:
      - rubocop
  eslint:
    jobs:
      - eslint
